version: '3.1'
services:
  api:
    build:
      context: .
      dockerfile: "docker/api/Dockerfile"
      args:
        ENVIRONMENT: "development"
    image: base/api:latest
    container_name: api
    ports:
      - 3000:3000
    entrypoint: ['yarn', 'start:dev']
    volumes:
      - .:/application
      - /application/node_modules
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: started
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
volumes:
  db-data: ~
